class MumbaiAreas {
  static const List<String> list = [
    'Air India Colony',
    'Airport Gate 8 Road',
    'Amar Mahal',
    'Andheri East',
    'Baiganwadi',
    'Bail Bazaar',
    'Ballard Estate',
    'Bhandup',
    'Bhandup Tank Road',
    'Bhuleshwar',
    'Borivali',
    'Byculla',
    'CST',
    'CST Road Nullah',
    'Carnac Bunder underpass',
    'Chembur',
    'Chembur East Bus Depot',
    'Colaba Causeway',
    'DN Nagar Metro',
    'Dadar TT',
    'Dahisar',
    'Dharavi',
    'Dockyard Road',
    'Dongri',
    'Elphinstone Bridge',
    'Five Gardens Underpass',
    'Fort',
    'Gandhi Market',
    'Ganesh Nagar Slum Slope',
    'Goregaon',
    'Goregaon Station',
    'Hindmata',
    'IC Colony',
    'JB Nagar',
    'Jerbai Wadia Road',
    'Kalina CST Road',
    'Kalina University',
    'Kandivali',
    'Kanjurmarg',
    'Khar West',
    'King\'s',
    'Kurar Village',
    'Kurla Station',
    'LBS Marg Bhandup Station',
    'LBS Road Phoenix Marketcity',
    'LJ Road',
    'Lady Jamshedji Road',
    'Linking Road National College',
    'Lok Rachana Society',
    'MG Road',
    'Madanpura',
    'Mahavir Nagar junction',
    'Mahim',
    'Mahul Village',
    'Mandapeshwar Creek edge',
    'Marine Lines',
    'Marol Naka',
    'Marve',
    'Matunga',
    'Mehul',
    'Metro Cinema',
    'Motilal Nagar',
    'Mulund',
    'Mulund Railway',
    'Naigaon Cross Road',
    'Nair Hospital',
    'Near Kirti College',
    'Oshiwara Nullah stretch',
    'Ovaripada slum slope',
    'P D\'Mello Road',
    'Panch Rasta',
    'Pant Nagar',
    'Pathanwadi',
    'Poinsur Depot',
    'Prabhadevi',
    'Princess Street corner',
    'Pushpa Park',
    'RB Kadam Marg',
    'RC Marg',
    'Regal',
    'SV Road',
    'Saat Rasta',
    'Saki Naka',
    'Santacruz West',
    'Sarojini Naidu Road',
    'Sewri',
    'Shell Colony',
    'Shimpoli Road',
    'Shivaji Nagar',
    'Siddharth Hospital',
    'Sion',
    'Trombay Road Sectors',
    'Tulsi Pipe Road station',
    'Vakola Nala stretch',
    'Vile Parle West',
    'Wadala',
    'Waterfield Road',
    'Western Express Highway slope',
    'Worli',
    'Worli Naka',
  ];
}
