class MumbaiAreas {
  static const List<String> list = [
    'Air India Colony',
    'Airport Gate 8 Road',
    'Amar Mahal Junction',
    'Andheri East',
    'Baiganwadi',
    'Bail Bazaar',
    'Ballard Estate',
    'Bhandup',
    'Bhandup Tank Road',
    'Bhuleshwar',
    'Borivali',
    'Byculla',
    'CST Road Nullah',
    'CST Subway (near St. Xavier\'s)',
    'Carnac Bunder underpass',
    'Chembur',
    'Chembur East Bus Depot',
    'Colaba Causeway',
    'DN Nagar Metro area',
    'Dadar TT',
    'Dahisar',
    'Dahisar Subway',
    'Dharavi',
    'Dockyard Road (Mazgaon)',
    'Dongri Circle',
    'Elphinstone Bridge (Lower Parel)',
    'Five Gardens Underpass',
    'Fort',
    'Gandhi Market Junction',
    'Ganesh Nagar Slum Slope',
    'Goregaon',
    'Goregaon Station Subway',
    'Hindmata Junction',
    'IC Colony Subway',
    'JB Nagar (Metro area)',
    'Jerbai Wadia Road',
    'Kalina CST Road',
    'Kalina University Junction',
    'Kandivali',
    'Kanjurmarg',
    'Khar West',
    'King\'s Circle',
    'Kurar Village',
    'Kurla Station (West & East)',
    'LBS Marg near Bhandup Station',
    'LBS Road near Phoenix Marketcity',
    'LJ Road Junction',
    'Lady Jamshedji Road',
    'Linking Road near National College',
    'Lok Rachana Society',
    'MG Road',
    'Madanpura',
    'Mahavir Nagar junction',
    'Mahim',
    'Mahul Village',
    'Mandapeshwar Creek edge',
    'Marine Lines Subway',
    'Marol Naka',
    'Marve',
    'Matunga',
    'Mehul Circle',
    'Metro Cinema Subway',
    'Motilal Nagar',
    'Mulund East',
    'Mulund Railway Subway',
    'Naigaon Cross Road',
    'Nair Hospital Junction',
    'Near Kirti College',
    'Oshiwara Nullah stretch',
    'Ovaripada slum slope',
    'P D\'Mello Road (near Masjid Bunder)',
    'Panch Rasta',
    'Pant Nagar',
    'Pathanwadi',
    'Poinsur Depot',
    'Prabhadevi',
    'Princess Street corner (Marine Lines Junction)',
    'Pushpa Park',
    'RB Kadam Marg',
    'RC Marg',
    'Regal Circle',
    'SV Road (Andheri Subway)',
    'SV Road (Khar Subway)',
    'Saat Rasta Junction',
    'Saki Naka Junction',
    'Santacruz West',
    'Sarojini Naidu Road',
    'Sewri',
    'Shell Colony',
    'Shimpoli Road',
    'Shivaji Nagar',
    'Siddharth Hospital area',
    'Sion Circle',
    'Trombay Road Sectors',
    'Tulsi Pipe Road near station',
    'Vakola Nala stretch',
    'Vile Parle West',
    'Wadala',
    'Waterfield Road',
    'Western Express Highway slope',
    'Worli',
    'Worli Naka (coastal backflow)',
  ];
}
